spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  health:
    redis:
      enabled: false

scheduler:
  enabled: false

otel:
  traces:
    sampler: always_off
  metrics:
    exporter: none
  logs:
    exporter: none
